# workflow의 이름
name : CI

# 해당 workflow가 언제 실행될 것인지에 대한 트리거를 지정
on :
  push :
    branches : [main] # main branch로 push 될 때 실행된다는 부분
  pull_request :
    branches : [main] # main branchfh pull request될 때 실행된다는 부분

# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있다
jobs:
  build :
    name : CI
    # 해당 jobs에서 아래의 steps들이 어떠한 환경에서 실행될 것인지를 지정
    runs-on : ubuntu-latest

    steps :
    # 작업에서 액세스할 수 있도록 GITHUb_WORKSPACE에서 저장소를 체크아웃 
      - uses : actions/checkout@v4
      - name : Set up JDK 1.7
        uses : actions/setup-java@v4
        with : 
          java-version : '17'
          distribution : 'zulu'

      - name : Grant execute permission for gradlew
        run : chmod +x ./gradlew
        shell : bash

      - name : Build with Gradle
        run : ./gradlew build
        shell : bash
